package schema

import "strings"

// CodeObjectOptions controls option-aware rendering and validation for owned
// code objects (ViewDef, ProcedureDef). The zero value preserves the default
// no-decoration behavior so existing callers see no change unless they
// explicitly pass a populated CodeObjectOptions to the *WithOptions helpers.
//
// Apply-owned decoration: both OwnershipNotice and DocPreamble are
// apply-owned, not declaration-owned. They are injected into the live SQL
// only by Apply*WithOptions and are tolerated (but not required) by
// Validate*WithOptions. Validate-only callers may pass options without
// forcing the markers to exist in the live database.
//
// Intended usage is one central config built once in bootstrap and passed
// to ApplyViewsWithOptions / ValidateViewsWithOptions /
// ApplyProceduresWithOptions / ValidateProceduresWithOptions rather than
// repeated per-definition boilerplate:
//
//	opts := schema.CodeObjectOptions{
//	    OwnershipNotice: schema.DefaultOwnershipNotice,
//	    DocPreamble:     "Generated by bootstrap. See docs/schema.md.",
//	}
//	if err := schema.ApplyViewsWithOptions(ctx, db, d, opts, views...); err != nil {
//	    return err
//	}
//	if err := schema.ValidateViewsWithOptions(ctx, db, d, opts, views...); err != nil {
//	    return err
//	}
//
// Render order when both fields are set: DocPreamble first, then
// OwnershipNotice, then payload. Each non-empty field is rendered as a
// `/* ... */` SQL block comment followed by a single space. Validate*WithOptions
// strips this exact ordered prefix from the live text before canonical
// comparison; live text that begins with a different leading comment will
// still report drift.
type CodeObjectOptions struct {
	// OwnershipNotice is an opt-in apply-owned marker the option-aware Apply*
	// helpers prepend to the rendered view body or procedure definition as a
	// SQL block comment. When empty (the default) nothing is emitted.
	//
	// Validate*WithOptions tolerates absence of the marker in live text:
	// stripping is best-effort, and live objects applied by bare helpers (or
	// out-of-band with no notice) still validate cleanly against the same
	// declared body. Different leading comments — including a stale notice
	// that no longer matches the configured value — still report drift.
	//
	// Engine notes:
	//   - SQLite: comment survives in sqlite_master.sql.
	//   - MSSQL:  comment survives in sys.sql_modules.definition.
	//   - Postgres: pg_get_viewdef discards comments when it reconstructs the
	//     SELECT, so the notice will land in the live CREATE statement but
	//     will not be visible when an operator reads pg_get_viewdef output.
	//     This does not produce false drift because Postgres view validation
	//     is existence-only (see ErrViewBodyComparisonUnsupported).
	OwnershipNotice string

	// DocPreamble is an optional caller-controlled doc comment the
	// option-aware Apply* helpers prepend to the rendered view body or
	// procedure definition as a SQL block comment. Rendered before
	// OwnershipNotice when both are set. Intended for caller commentary
	// (purpose, contact, link to runbook) and is not treated as proof of
	// ownership — it is metadata only.
	//
	// Validate*WithOptions strips the exact configured DocPreamble from live
	// text alongside OwnershipNotice. Absent or different leading comments
	// follow the same tolerance/drift rules as OwnershipNotice.
	DocPreamble string
}

// DefaultOwnershipNotice is the canonical chuck-owned ownership notice text
// suggested by issue #84. Deliberately soft: it says out-of-band changes
// "may" fail validation or be overwritten because the explicit Validate* /
// Apply* lanes leave that choice to the caller, and Postgres view validation
// is existence-only today (see ErrViewBodyComparisonUnsupported), so a
// stronger promise would be dishonest. The notice embeds the chuck GitHub
// URL rather than the bare project name so DB readers who do not know what
// "chuck" is can find the project directly.
const DefaultOwnershipNotice = "Owned by https://github.com/catgoose/chuck. Do not edit in database.\n" +
	"Out-of-band changes may fail validation or be overwritten by apply/bootstrap."

// renderOwnershipComment formats a notice as a SQL block comment, or returns
// "" when no notice is set. Engine-agnostic `/* ... */` syntax is accepted by
// SQLite, MSSQL, and Postgres at the body / definition payload positions where
// chuck injects it.
func renderOwnershipComment(notice string) string {
	if notice == "" {
		return ""
	}
	return "/* " + notice + " */"
}

// renderApplyPrefix returns the full configured comment prefix that
// Apply*WithOptions prepends to the rendered body / definition payload.
// DocPreamble is rendered first, then OwnershipNotice; each non-empty field
// contributes a `/* ... */ ` segment (block comment plus single trailing
// space). When both fields are empty, returns "".
func renderApplyPrefix(opts CodeObjectOptions) string {
	var b strings.Builder
	if c := renderOwnershipComment(opts.DocPreamble); c != "" {
		b.WriteString(c)
		b.WriteByte(' ')
	}
	if c := renderOwnershipComment(opts.OwnershipNotice); c != "" {
		b.WriteString(c)
		b.WriteByte(' ')
	}
	return b.String()
}

// applyOwnershipNoticePrefix returns the body or definition payload prefixed
// with the rendered apply-comment prefix when one is set, otherwise the
// payload unchanged. A single space separates each comment from the next
// segment to keep the resulting statement well-formed regardless of whether
// the payload starts with a SELECT keyword (views), a parameter declaration
// (procedures), or an AS keyword (zero-parameter procedures).
func applyOwnershipNoticePrefix(payload string, opts CodeObjectOptions) string {
	prefix := renderApplyPrefix(opts)
	if prefix == "" {
		return payload
	}
	return prefix + payload
}

// stripConfiguredApplyPrefix strips the exact configured DocPreamble and
// OwnershipNotice comment prefixes (in that order) from the front of live
// text, plus any leading whitespace, returning the remainder. When a
// configured prefix is not present the function leaves the text unchanged
// for that segment — a configured-but-absent marker is tolerated so
// validate-only callers can pass options without forcing markers into the
// live object. When no fields are configured, the function returns live
// unchanged.
func stripConfiguredApplyPrefix(live string, opts CodeObjectOptions) string {
	out := strings.TrimLeft(live, " \t\r\n")
	if c := renderOwnershipComment(opts.DocPreamble); c != "" {
		if strings.HasPrefix(out, c) {
			out = strings.TrimLeft(out[len(c):], " \t\r\n")
		}
	}
	if c := renderOwnershipComment(opts.OwnershipNotice); c != "" {
		if strings.HasPrefix(out, c) {
			out = strings.TrimLeft(out[len(c):], " \t\r\n")
		}
	}
	return out
}
