package schema

import "strings"

// CodeObjectOptions controls option-aware rendering and validation for owned
// code objects (ViewDef, ProcedureDef). The zero value preserves the default
// no-decoration behavior so existing callers see no change unless they
// explicitly pass a populated CodeObjectOptions to the *WithOptions helpers.
//
// Apply-owned decoration: both OwnershipNotice and DocPreamble are
// apply-owned, not declaration-owned. They are injected into the live SQL
// only by Apply*WithOptions and are tolerated (but not required) by
// Validate*WithOptions. Validate-only callers may pass options without
// forcing the markers to exist in the live database.
//
// For per-object documentation that should be declaration-owned — part of
// the object's own SQL identity and a drift signal when changed — use
// ViewDef.WithDocAnnotation / ProcedureDef.WithDocAnnotation instead. The
// declaration-owned annotation renders between DocPreamble and
// OwnershipNotice in the live SQL and is included in body-drift comparison.
//
// Intended usage is one central config built once in bootstrap and passed
// to ApplyViewsWithOptions / ValidateViewsWithOptions /
// ApplyProceduresWithOptions / ValidateProceduresWithOptions rather than
// repeated per-definition boilerplate:
//
//	opts := schema.CodeObjectOptions{
//	    OwnershipNotice: schema.DefaultOwnershipNotice,
//	    DocPreamble:     "Generated by bootstrap. See docs/schema.md.",
//	}
//	if err := schema.ApplyViewsWithOptions(ctx, db, d, opts, views...); err != nil {
//	    return err
//	}
//	if err := schema.ValidateViewsWithOptions(ctx, db, d, opts, views...); err != nil {
//	    return err
//	}
//
// Render order when fields are set: DocPreamble first, then any per-object
// declaration-owned doc annotation, then OwnershipNotice, then payload. Each
// non-empty segment is rendered as a `/* ... */` SQL block comment followed
// by a single space. Validate*WithOptions strips this exact ordered prefix
// from the live text before canonical comparison (keeping the
// declaration-owned annotation, which participates in comparison); live text
// that begins with a different leading comment will still report drift.
type CodeObjectOptions struct {
	// OwnershipNotice is an opt-in apply-owned marker the option-aware Apply*
	// helpers prepend to the rendered view body or procedure definition as a
	// SQL block comment. When empty (the default) nothing is emitted.
	//
	// Validate*WithOptions tolerates absence of the marker in live text:
	// stripping is best-effort, and live objects applied by bare helpers (or
	// out-of-band with no notice) still validate cleanly against the same
	// declared body. Different leading comments — including a stale notice
	// that no longer matches the configured value — still report drift.
	//
	// Engine notes:
	//   - SQLite: comment survives in sqlite_master.sql.
	//   - MSSQL:  comment survives in sys.sql_modules.definition.
	//   - Postgres: pg_get_viewdef discards comments when it reconstructs the
	//     SELECT, so the notice will land in the live CREATE statement but
	//     will not be visible when an operator reads pg_get_viewdef output.
	//     This does not produce false drift because Postgres view validation
	//     is existence-only (see ErrViewBodyComparisonUnsupported).
	OwnershipNotice string

	// DocPreamble is an optional caller-controlled doc comment the
	// option-aware Apply* helpers prepend to the rendered view body or
	// procedure definition as a SQL block comment. Rendered before
	// OwnershipNotice when both are set. Intended for caller commentary
	// (purpose, contact, link to runbook) and is not treated as proof of
	// ownership — it is metadata only.
	//
	// Validate*WithOptions strips the exact configured DocPreamble from live
	// text alongside OwnershipNotice. Absent or different leading comments
	// follow the same tolerance/drift rules as OwnershipNotice.
	DocPreamble string
}

// DefaultOwnershipNotice is the canonical chuck-owned ownership notice text
// suggested by issue #84. Deliberately soft: it says out-of-band changes
// "may" fail validation or be overwritten because the explicit Validate* /
// Apply* lanes leave that choice to the caller, and Postgres view validation
// is existence-only today (see ErrViewBodyComparisonUnsupported), so a
// stronger promise would be dishonest. The notice embeds the chuck GitHub
// URL rather than the bare project name so DB readers who do not know what
// "chuck" is can find the project directly.
const DefaultOwnershipNotice = "Owned by https://github.com/catgoose/chuck. Do not edit in database.\n" +
	"Out-of-band changes may fail validation or be overwritten by apply/bootstrap."

// renderOwnershipComment formats a notice as a SQL block comment, or returns
// "" when no notice is set. Engine-agnostic `/* ... */` syntax is accepted by
// SQLite, MSSQL, and Postgres at the body / definition payload positions where
// chuck injects it.
func renderOwnershipComment(notice string) string {
	if notice == "" {
		return ""
	}
	return "/* " + notice + " */"
}

// renderApplyPrefix returns the full configured comment prefix that
// Apply*WithOptions prepends to the rendered body / definition payload.
// Render order: DocPreamble (apply-owned), declared per-object annotation
// (declaration-owned), OwnershipNotice (apply-owned). Each non-empty
// segment contributes a `/* ... */ ` chunk (block comment plus single
// trailing space). When all three are empty, returns "".
func renderApplyPrefix(opts CodeObjectOptions, declaredAnnotation string) string {
	var b strings.Builder
	if c := renderOwnershipComment(opts.DocPreamble); c != "" {
		b.WriteString(c)
		b.WriteByte(' ')
	}
	if c := renderOwnershipComment(declaredAnnotation); c != "" {
		b.WriteString(c)
		b.WriteByte(' ')
	}
	if c := renderOwnershipComment(opts.OwnershipNotice); c != "" {
		b.WriteString(c)
		b.WriteByte(' ')
	}
	return b.String()
}

// applyOwnershipNoticePrefix returns the body or definition payload prefixed
// with the rendered apply-comment prefix when one is set, otherwise the
// payload unchanged. A single space separates each comment from the next
// segment to keep the resulting statement well-formed regardless of whether
// the payload starts with a SELECT keyword (views), a parameter declaration
// (procedures), or an AS keyword (zero-parameter procedures).
//
// declaredAnnotation is the per-object declaration-owned doc annotation
// (ViewDef.DocAnnotation / ProcedureDef.DocAnnotation); pass "" when not
// declared. When non-empty it is rendered between the caller-level
// DocPreamble and the caller-level OwnershipNotice so callers reading the
// live SQL see preamble → per-object annotation → ownership.
func applyOwnershipNoticePrefix(payload string, opts CodeObjectOptions, declaredAnnotation string) string {
	prefix := renderApplyPrefix(opts, declaredAnnotation)
	if prefix == "" {
		return payload
	}
	return prefix + payload
}

// stripConfiguredApplyPrefix strips the exact configured DocPreamble and
// OwnershipNotice comment prefixes from the front of live text in their
// declared render order, plus any leading whitespace. When a per-object
// declaration-owned doc annotation is declared, it is recognized in its
// natural slot (between DocPreamble and OwnershipNotice) and retained in
// the returned string so it can participate in canonical drift comparison.
// Configured-but-absent apply-owned markers are tolerated; an absent or
// mismatched declaration-owned annotation reports as body drift because
// declared identity has changed.
func stripConfiguredApplyPrefix(live string, opts CodeObjectOptions, declaredAnnotation string) string {
	docComment := renderOwnershipComment(opts.DocPreamble)
	annComment := renderOwnershipComment(declaredAnnotation)
	ownComment := renderOwnershipComment(opts.OwnershipNotice)

	out := strings.TrimLeft(live, " \t\r\n")
	if docComment != "" && strings.HasPrefix(out, docComment) {
		out = strings.TrimLeft(out[len(docComment):], " \t\r\n")
	}
	kept := ""
	if annComment != "" && strings.HasPrefix(out, annComment) {
		kept = annComment
		out = strings.TrimLeft(out[len(annComment):], " \t\r\n")
	}
	if ownComment != "" && strings.HasPrefix(out, ownComment) {
		out = strings.TrimLeft(out[len(ownComment):], " \t\r\n")
	}
	if kept != "" {
		return kept + " " + out
	}
	return out
}
